AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for my S3 Bucket view count Website"

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'POST'"
      AllowHeaders: "'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range'"
      AllowOrigin: "'*'"

Resources:
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: VisitCounter
      PrimaryKey:
        Name: SourceIP
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  VisitCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        VisitCount:
          Type: Api
          Properties:
            Path: /visitors
            Method: post
      Environment:
        Variables:
          databaseName: 'VisitCounter'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable

Outputs:
  WebsiteCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume Count Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitors/"
